document_root: www
docker_compose:
  overrides:
    queue:
      image: rabbitmq:3-management
      hostname: terra-rabbit
      ports:
        - '8080:15672'
        - '5672'
    app:
      links:
        - queue

hooks:
  build: |
    drush dl drupal-7.38
    mv drupal-7.38 www
    cp www/sites/default/default.settings.php www/sites/default/settings.php
    echo "\$conf['amqp_server'] = array(
      'host' => 'queue',
      'port' => 5672,
      'user' => 'guest',
      'pass' => 'guest',
      'queue' => 'terra',
    );" >> www/sites/default/settings.php
    cd www/sites/all/modules
    git clone https://github.com/albatrossdigital/terra_ui
    cd terra_ui
    composer install
    
  enable_first: |
    drush {{alias}} site-install standard --db-url=mysql://drupal:drupal@database/drupal -y
    drush {{alias}} en -y terra_ui
    drush {{alias}} uli
